_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-x86_64
model:
    value: xgb
test_year:
    value: "2023"
