wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709758473.948676
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.15.11
      8:
      - 5
      13: darwin-x86_64
model:
  desc: null
  value: rf
test_year:
  desc: null
  value: '2023'
